// جدولُ الإنجليزيّة — مفتاحُه النصُّ العربيُّ نفسُه.
//
// **وما لا يُوجد هنا يُعرض بالعربيّة**، لا برمزٍ ولا بفراغ. فالجدولُ ينمو
// دفعةً بعد دفعة والتطبيقُ يعمل في كلّ حال — وهذا ما تقيسه
// `i18n_coverage_test.dart`: تُطبع نسبةُ المترجَم، ويُمنع أن تنقص.
//
// **ولا تُترجم أسماءُ الخدمات والمزوّدين والأقسام:** تلك تأتي من قاعدة
// البيانات كما كتبها أصحابُها، ولا شأنَ للتطبيق بها.
//
// ولا يُكتب هنا نصٌّ فيه `$` — ما يحمل قيمةً تُدرَج يُبنى بـ`trf` بنائبٍ
// مرقَّم، لأنّ ترتيبَ الأجزاء يختلف بين اللغتين.
const Map<String, String> englishStrings = {
  '(تجريبي) محاكاة قبول الإدارة': '(Demo) simulate admin approval',
  '{0} حجزاً منفَّذاً': '{0} bookings completed',
  '{0} من 5': '{0} of 5',
  '{0}٪': '{0}%',
  '؟': '?',
  'آخر ظهور {0}': 'Last seen {0}',
  'آراء العملاء': 'Customer reviews',
  'أبحث عن خدمات وأخطّط لحفل زفافي': 'I am looking for services and planning my wedding',
  'أبلغنا بالحوالة': 'Report your transfer',
  'أبين': 'Abyan',
  'أحد': 'Sun',
  'أخرى': 'Other',
  'أدخل رمز القفل': 'Enter your lock code',
  'أربعاء': 'Wed',
  'أربعة أرقام': 'Four digits',
  'أرسل': 'Send',
  'أرسل «فرحتي» لمن يجهّز عرسه': 'Send Farhati to someone planning their wedding',
  'أرسل التسجيل': 'Send recording',
  'أرفق': 'Attach',
  'أرقامك': 'Your numbers',
  'أريد تقديم خدمة': 'I want to offer a service',
  'أزل الموقع': 'Remove location',
  'أزل من المفضّلة': 'Remove from favourites',
  'أسماء الخدمات والمزوّدين تبقى كما كتبها أصحابها.': 'Service and provider names stay as their owners wrote them.',
  'أضف': 'Add',
  'أضف صورة': 'Add a photo',
  'أضف للمفضّلة': 'Add to favourites',
  'أضف ما تقدّمه بسعره وعربونه، ليظهر للعملاء في الاستكشاف.': 'Add what you offer with its price and deposit, so customers see it in Explore.',
  'أضف ما يوضّح موقفك…': 'Add anything that supports your case…',
  'أضف مقطع فيديو': 'Add a video',
  'أضف مقطعاً صوتياً': 'Add an audio clip',
  'أضف مهمّة…': 'Add a task…',
  'أضِفه إلى خطة العرس': 'Add it to the wedding plan',
  'أطفئه': 'Turn off',
  'أعرض خدماتي وأستقبل الحجوزات': 'I list my services and take bookings',
  'أعلى السعر لا يكون أقلّ من أدناه.': 'The maximum price cannot be below the minimum.',
  'أعِد الرمز للتأكيد': 'Repeat the code to confirm',
  'أغلق اليوم': 'Close this day',
  'أغلقتَه': 'You closed it',
  'أغلقها': 'Close it',
  'أغلقها إن حُلّت مشكلتك. تبقى المحادثة محفوظة، ويمكنك فتح تذكرة جديدة متى شئت.': 'Close it once your problem is solved. The conversation stays saved, and you can open a new ticket any time.',
  'أقربها {0} · {1}': 'Nearest {0} · {1}',
  'أكمل المبلغ {0}': 'Pay the rest {0}',
  'أكمل ملفك': 'Complete your profile',
  'ألغِ التسجيل': 'Cancel recording',
  'أمانة العاصمة': 'Amanat Al-Asimah',
  'أنا عروس': 'I am the bride',
  'أنا عريس': 'I am the groom',
  'أنت': 'You',
  'أنشئ حسابك لتبدأ تجهيز عرسك': 'Create your account and start planning your wedding',
  'أنشئ خطتك': 'Create your plan',
  'أهلاً بك': 'Welcome',
  'أي تفاصيل يحتاجها مقدّم الخدمة': 'Any details the provider needs',
  'أيام': 'days',
  'أُطفئ قفل التطبيق.': 'App lock turned off.',
  'أُغلقت التذكرة.': 'Ticket closed.',
  'أُلغي الحجز.': 'Booking cancelled.',
  'أُوقفت الخدمة': 'Service suspended',
  'إب': 'Ibb',
  'إجمالي الأرباح': 'Total earnings',
  'إجمالي الحجز': 'Booking total',
  'إجمالي الحجوزات': 'Total bookings',
  'إخفاء المنجَز': 'Hide completed',
  'إرسال': 'Send',
  'إرسال التقييم': 'Submit review',
  'إشعارات الحجوزات والرسائل': 'Booking and message notifications',
  'إضافة': 'Add',
  'إعادة المحاولة': 'Try again',
  'إعلان': 'Advertisement',
  'إغلاق': 'Close',
  'إغلاق {0}': 'Close {0}',
  'إغلاق التذكرة': 'Close ticket',
  'إكمال المبلغ': 'Pay the balance',
  'إلغاء': 'Cancel',
  'إلغاء الحجز': 'Cancel booking',
  'إلى (اختياري)': 'To (optional)',
  'إن كان لديك كود': 'If you have a code',
  'إنشاء الحساب': 'Create account',
  'إنشاء الخطة': 'Create plan',
  'إيقاف': 'Stop',
  'ابحث': 'Search',
  'ابحث عن مكان، أو الصق رابطه': 'Search for a place, or paste its link',
  'ابحث عن…': 'Search…',
  'ابدأ الحديث': 'Start the conversation',
  'ابدأ خطة عرسك': 'Start your wedding plan',
  'ابدأ رحلتك': 'Start your journey',
  'ابدأ من «استكشف» واحجز خدمتك القادمة': 'Start from Explore and book your next service',
  'ابدأ من «استكشف» واختر أول خدمة لعرسك.': 'Start from Explore and pick the first service for your wedding.',
  'اثنين': 'Mon',
  'اجعله الافتراضي': 'Make it default',
  'اجعلها الافتراضية': 'Make it default',
  'احجز': 'Book',
  'احذف': 'Delete',
  'احذف المهمّة': 'Delete task',
  'احفظ رقم محفظتك مرّةً واحدة، فيملأ نفسه في كل إبلاغٍ بحوالة.': 'Save your wallet number once and it fills itself in every time you report a transfer.',
  'احفظ عنوان بيت العرس مرّةً واحدة، فيملأ نفسه في كل حجزٍ بعدها.': 'Save the wedding address once and it fills itself in on every booking after.',
  'اختر المحافظة': 'Choose a governorate',
  'اختر الوسيلة التي حوّلت بها.': 'Choose the method you transferred with.',
  'اختر تاريخ العرس': 'Choose the wedding date',
  'اختر تاريخ العرس.': 'Choose the wedding date.',
  'اختر رمزاً من أربعة أرقام': 'Choose a four-digit code',
  'اختر ما يصفك لنبدأ من مكانك الصحيح': 'Pick what describes you so we start in the right place',
  'اختر مقطعاً صوتياً': 'Choose an audio clip',
  'اختر ملفاً': 'Choose a file',
  'اختر من المعرض': 'Choose from gallery',
  'اختر نوع الحساب': 'Choose your account type',
  'اختيار من المعرض': 'Choose from gallery',
  'اخرج وأعد الدخول': 'Sign out and back in',
  'ادفع العربون {0}': 'Pay the deposit {0}',
  'استعادة كلمة المرور': 'Reset password',
  'استكشف': 'Explore',
  'استمع قبل أن تحجز': 'Listen before you book',
  'اسم الخدمة': 'Service name',
  'اسم الخطة': 'Plan name',
  'اسم المحل أو القاعة': 'Shop or hall name',
  'اسم المنشأة': 'Business name',
  'اسم صاحب المحفظة': 'Wallet holder name',
  'اشتراكك': 'Your subscription',
  'اشترك': 'Subscribe',
  'اشرح ما حدث بالتفصيل…': 'Describe what happened in detail…',
  'اشرح مشكلتك بالتفصيل…': 'Describe your problem in detail…',
  'اضغط أيَّ يومٍ لتغلقه إن كان عندك ارتباط.': 'Tap any day to close it if you are busy.',
  'اضغط لإنشاء الخطة': 'Tap to create the plan',
  'اضغط لعرض حجوزاتك': 'Tap to see your bookings',
  'اعتذار': 'Apology',
  'افتح الموقع في الخرائط': 'Open location in Maps',
  'افتح النزاع': 'Open a dispute',
  'افتح في الخرائط': 'Open in Maps',
  'افتحه': 'Open',
  'اقتراح': 'Suggestion',
  'اقصصه ثم أعد الرفع.': 'Trim it and upload again.',
  'اكتب اسم الخدمة وسعرها، واختر قسمها.': 'Enter the service name and price, and pick its category.',
  'اكتب اسم محلّك أو قاعتك.': 'Enter your shop or hall name.',
  'اكتب اسمك كاملاً.': 'Enter your full name.',
  'اكتب اسمك ورقمك واختر محافظتك.': 'Enter your name and phone, and choose your governorate.',
  'اكتب البريد وكلمة المرور.': 'Enter your email and password.',
  'اكتب الرمز الواصل إلى بريدك.': 'Enter the code sent to your email.',
  'اكتب العنوان بتفصيلٍ يكفي لِمن يصل إليه.': 'Write the address in enough detail for someone finding it.',
  'اكتب رقم المحفظة أو الحساب.': 'Enter the wallet or account number.',
  'الأقرب إليّ': 'Nearest to me',
  'الأيام المغلقة': 'Closed days',
  'الإجمالي {0}': 'Total {0}',
  'الإشعارات': 'Notifications',
  'الإصدار 1.0.0': 'Version 1.0.0',
  'الإعدادات': 'Settings',
  'الاسم': 'Name',
  'الاسم الكامل': 'Full name',
  'الافتراضي': 'Default',
  'الباقات والاشتراك': 'Plans and subscription',
  'البريد الإلكتروني': 'Email',
  'البيضاء': 'Al-Bayda',
  'التبديل إلى وضع مقدّم الخدمة': 'Switch to provider mode',
  'التعريف': 'About',
  'التقاط صورة': 'Take a photo',
  'التقييم': 'Rating',
  'الجوف': 'Al-Jawf',
  'الحديدة': 'Al-Hudaydah',
  'الخطوة ١ من ٢': 'Step 1 of 2',
  'الخطوة ٢ من ٢': 'Step 2 of 2',
  'الدعم': 'Support',
  'الرئيسية': 'Home',
  'الرمز أربعة أرقام.': 'The code is four digits.',
  'الرمزان لم يتطابقا. اختر رمزاً من جديد.': 'The codes did not match. Choose a code again.',
  'السبب': 'Reason',
  'السبب (اختياري)': 'Reason (optional)',
  'السعر': 'Price',
  'السعر (ر.ي)': 'Price (YER)',
  'الشهر التالي': 'Next month',
  'الشهر السابق': 'Previous month',
  'الصور': 'Photos',
  'الصور والمقاطع': 'Photos and videos',
  'الضالع': 'Ad-Dali',
  'الطلبات': 'Requests',
  'العربون {0}٪': 'Deposit {0}%',
  'العربون: {0}٪': 'Deposit: {0}%',
  'العروض والإعلانات': 'Offers and promotions',
  'العناوين': 'Addresses',
  'العنوان': 'Address',
  'العودة إلى وضع العميل': 'Back to customer mode',
  'القسم': 'Category',
  'القفل مطفأ': 'Lock is off',
  'القفل مفعّل': 'Lock is on',
  'الكريمي': 'Al-Kuraimi',
  'الكل': 'All',
  'اللغة': 'Language',
  'المحادثات': 'Chats',
  'المحافظة': 'Governorate',
  'المحويت': 'Al-Mahwit',
  'المدفوع': 'Paid',
  'المزيد': 'More',
  'المفضّلة': 'Favourites',
  'المكلا': 'Mukalla',
  'الملف الشخصي': 'Profile',
  'المنطقة، والشارع، وعلامةٌ مميّزة': 'Area, street, and a landmark',
  'المهرة': 'Al-Mahrah',
  'الميزانية': 'Budget',
  'النزاعات': 'Disputes',
  'الوحدة': 'Unit',
  'الوصف': 'Description',
  'بانتظار المزوّد {0}': 'Awaiting provider {0}',
  'بعد خمس دقائق': 'After five minutes',
  'بعد دقيقة': 'After a minute',
  'بعد ربع ساعة': 'After fifteen minutes',
  'بعد ساعة': 'After an hour',
  'بيت العرس، القاعة، بيت العروس…': 'Wedding house, the hall, the bride’s house…',
  'تأكيد التنفيذ': 'Confirm completion',
  'تراجع': 'Undo',
  'تسجيل الخروج': 'Sign out',
  'تسجيل الخروج؟': 'Sign out?',
  'تعديل': 'Edit',
  'تعديل الاسم والتعريف': 'Edit name and about',
  'تعديل الخدمة': 'Edit service',
  'تعديل الخطة': 'Edit plan',
  'تعديل العنوان': 'Edit address',
  'تعديل الوسيلة': 'Edit method',
  'تعذّر تشغيل المقطع': 'Could not play the clip',
  'تعذّر فتح الرابط — افتح {0} في متصفّحك.': 'Could not open the link — open {0} in your browser.',
  'تعذّرت المشاركة من هذا الجهاز.': 'Sharing is not available on this device.',
  'تعز': 'Taiz',
  'تعليقك (اختياري)': 'Your comment (optional)',
  'تفاصيل تقنية': 'Technical details',
  'تقويمي': 'My calendar',
  'ثانية': 'second',
  'ثلاثاء': 'Tue',
  'ثمانية أحرف فأكثر.': 'Eight characters or more.',
  'جارٍ التحميل…': 'Loading…',
  'جديد': 'New',
  'جرّب قسماً آخر أو امسح البحث.': 'Try another category or clear the search.',
  'جمعة': 'Fri',
  'جوالي': 'Jawali',
  'حجة': 'Hajjah',
  'حجز': 'booking',
  'حجوزات منفّذة': 'Completed bookings',
  'حجوزاتك السابقة محفوظة أدناه': 'Your past bookings are saved below',
  'حجوزاتي': 'My bookings',
  'حذف': 'Delete',
  'حذف العنوان؟': 'Delete this address?',
  'حذف الوسيلة؟': 'Delete this method?',
  'حسابي': 'My account',
  'حضرموت': 'Hadhramaut',
  'حفظ': 'Save',
  'حوالة بنكية': 'Bank transfer',
  'حوّل إلى': 'Transfer to',
  'حوّلتُ المبلغ — أبلغ الإدارة': 'I sent the money — notify the team',
  'حُذف {0}': '{0} deleted',
  'حُفظ الشعار': 'Logo saved',
  'حُفظت بياناتك.': 'Your details are saved.',
  'خدمات': 'Services',
  'خدماتي': 'My services',
  'خدماتٌ لك': 'Services for you',
  'خدمة جديدة': 'New service',
  'خروج': 'Sign out',
  'خصومات المزوّدين والحملات': 'Provider discounts and campaigns',
  'خطة العرس': 'Wedding plan',
  'خميس': 'Thu',
  'دقيقة': 'minute',
  'ذمار': 'Dhamar',
  'رابط التنزيل غير صالح — راجع الإدارة.': 'The download link is not valid — contact support.',
  'راسل {0}': 'Message {0}',
  'رقم الجوال': 'Phone number',
  'رقم المحفظة أو الحساب': 'Wallet or account number',
  'رمزٌ خاطئ — بقيت {0} محاولات.': 'Wrong code — {0} attempts left.',
  'ريمة': 'Raymah',
  'رُفض الحجز — أُعيد للعميل كل ما دفعه.': 'Booking declined — everything the customer paid was returned.',
  'ساعة': 'hour',
  'سبت': 'Sat',
  'ستحتاج إلى بريدك وكلمة مرورك للدخول مرّةً أخرى.': 'You will need your email and password to sign in again.',
  'ستصلك هنا حجوزات العملاء على خدماتك بعد توثيق ملفك.': 'Customer bookings for your services will arrive here once your profile is verified.',
  'سفر، مناسبة عائلية، صيانة…': 'Travel, a family occasion, maintenance…',
  'سقطرى': 'Socotra',
  'سياسة الخصوصية': 'Privacy policy',
  'سيُغلق حسابُك على هذا الجهاز ويُزال القفل. وتدخل من جديد ببريدك وكلمة مرورك. ولا يضيع شيءٌ من حجوزاتك ولا محادثاتك — كلُّها في حسابك لا في الجهاز.': 'You will be signed out on this device and the lock removed. Sign back in with your email and password. Nothing is lost — your bookings and chats live in your account, not on the device.',
  'سُجّل تنفيذ الحجز، وفُتح للعميل باب التقييم.': 'The booking is marked done, and the customer can now leave a review.',
  'شارك': 'Share',
  'شارك التطبيق': 'Share the app',
  'شبوة': 'Shabwah',
  'شروط الاستخدام': 'Terms of use',
  'شغّل بيانات الجوال أو الواي‑فاي، ثم أعد المحاولة.': 'Turn on mobile data or Wi‑Fi, then try again.',
  'شكراً — نُشر تقييمك.': 'Thank you — your review is published.',
  'شهرٌ مفتوحٌ كلُّه': 'A whole month open',
  'صدرت نسخة {0}': 'Version {0} is out',
  'صعدة': 'Saada',
  'صنعاء': 'Sana’a',
  'صورة': 'Photo',
  'طرق الدفع': 'Payment methods',
  'طلب حذف الحساب': 'Request account deletion',
  'طلبك قيد المراجعة — لن تستقبل حجوزات حتى تُقبل مستنداتك.': 'Your application is under review — you will not receive bookings until your documents are accepted.',
  'عادت الخدمة للعرض': 'The service is listed again',
  'عدد التقييمات': 'Reviews',
  'عدد الضيوف': 'Guests',
  'عدن': 'Aden',
  'عرض': 'Show',
  'عمران': 'Amran',
  'عميل': 'Customer',
  'عن التطبيق': 'About',
  'عندي مشكلة في هذا الحجز': 'I have a problem with this booking',
  'عنوان': 'Address',
  'عنوان جديد': 'New address',
  'غير محدّدة': 'Not set',
  'فعّله': 'Turn on',
  'فواتيري': 'My invoices',
  'فوراً': 'Immediately',
  'فُتح النزاع — تنظر فيه الإدارة وتصلك ردودها هنا.': 'The dispute is open — the team is reviewing it and their replies reach you here.',
  'فُعّل قفل التطبيق.': 'App lock turned on.',
  'قاعة التاج': 'Al‑Taj Hall',
  'قاعة التاج — باقة شاملة': 'Al‑Taj Hall — full package',
  'قبول': 'Accept',
  'قفل التطبيق': 'App lock',
  'قيد التأكيد': 'Awaiting confirmation',
  'قيد المراجعة': 'Under review',
  'قيّم الخدمة': 'Rate the service',
  'قُبل الحجز — أُغلق اليوم في تقويمك ووصل العميل إشعار.': 'Booking accepted — the day is closed in your calendar and the customer was notified.',
  'قُبل حجزك، وصلتك رسالة، تأكّدت حوالتك': 'Booking accepted, message received, transfer confirmed',
  'كل المحافظات': 'All governorates',
  'كلمة المرور قصيرة جداً (8 أحرف على الأقل).': 'Password is too short (8 characters minimum).',
  'كما هو مسجَّلٌ لديهم': 'As registered with them',
  'كيف كانت {0}؟': 'How was {0}?',
  'لا بدّ من التحديث': 'Update required',
  'لا تقييم بعد': 'No reviews yet',
  'لا توجد خدمات مطابقة': 'No matching services',
  'لا حجوزات بعد': 'No bookings yet',
  'لا حجوزات قادمة': 'No upcoming bookings',
  'لا خدمات بعد': 'No services yet',
  'لا طرق دفع محفوظة': 'No saved payment methods',
  'لا طلبات بعد': 'No requests yet',
  'لا عناوين محفوظة': 'No saved addresses',
  'لا مزوّدين في هذا القسم': 'No providers in this category',
  'لا ملف مقدّم خدمة': 'No provider profile',
  'لا يوجد اتصال بالإنترنت': 'No internet connection',
  'لاحقاً': 'Later',
  'لحج': 'Lahij',
  'للحجز': 'per booking',
  'للحجز / لليوم / لليلة': 'per booking / per day / per night',
  'لم تُضبط وسائل التحويل بعد': 'No transfer methods set up yet',
  'لم تُقدّم طلباً بعد.': 'You have not applied yet.',
  'لم يصلني — أعد الإرسال': 'I did not get it — resend',
  'لم يُدفع بعد': 'Not paid yet',
  'لن يستطيع أحد أن يحجزك في هذا اليوم. والسبب لك وحدك — لا يراه العميل.': 'No one will be able to book you on this day. The reason is for you alone — the customer never sees it.',
  'لنطاق سعري': 'for a price range',
  'مأرب': 'Marib',
  'مؤكّد {0}': 'Confirmed {0}',
  'ما الذي أعجبك؟ وما الذي كان يمكن أن يكون أفضل؟': 'What did you like? And what could have been better?',
  'ما الذي تشمله الباقة؟': 'What does the package include?',
  'ما الذي تقدّمه؟ ومنذ متى؟ وما الذي يميّزك؟': 'What do you offer? For how long? And what sets you apart?',
  'ما يُستردّ لك يُحسب حسب سياسة الإلغاء وقُرب الموعد. الإلغاء لا رجعة فيه.': 'What you get back is worked out from the cancellation policy and how close the date is. Cancelling cannot be undone.',
  'متابعة النزاع': 'Follow the dispute',
  'متاح': 'Available',
  'متّصل الآن': 'Online now',
  'محجوز': 'Booked',
  'مدفوع {0}': 'Paid {0}',
  'مرحباً بك في فرحتي': 'Welcome to Farhati',
  'مرفوض': 'Rejected',
  'مزوّد موثَّق': 'Verified provider',
  'مزوّدون مميّزون': 'Featured providers',
  'مستحقّاتي': 'My earnings',
  'مستندات التوثيق': 'Verification documents',
  'معروضة': 'Listed',
  'مقدّم الخدمة': 'Service provider',
  'مقدّم خدمة': 'Service provider',
  'مقدّمو الخدمة': 'Service providers',
  'مقطع صوتي': 'Voice note',
  'ملف': 'File',
  'ملفي': 'My profile',
  'ملفّي': 'My profile',
  'ملفّي كما يراه العميل': 'My profile as the customer sees it',
  'مميّز': 'Featured',
  'موقع المحلّ': 'Shop location',
  'موقع محلّك': 'Your shop location',
  'موقوفة': 'Suspended',
  'نحفظ رقم محفظتك التي تُحوّل منها ليملأ نفسه عند الإبلاغ بالحوالة — ولا نحفظ بطاقات ولا أرقاماً سرّية.': 'We save the wallet number you transfer from so it fills itself in when you report a transfer — we never save cards or secret numbers.',
  'نزّل التحديث': 'Download the update',
  'نزّلها': 'Download',
  'نسختُك لم تعد تعمل مع الخدمة. نزّل نسخة {0} لتُكمل.': 'Your version no longer works with the service. Download version {0} to continue.',
  'نسيتَ الرمز؟': 'Forgot your code?',
  'نسيتُ الرمز': 'I forgot the code',
  'نغمة الإشعار': 'Notification sound',
  'هذا اليوم محجوز: {0}': 'This day is booked: {0}',
  'هذا ما يقرؤه العميل في صفحتك قبل أن يحجز.': 'This is what the customer reads on your page before booking.',
  'وسيلة جديدة': 'New method',
  'يملأ نموذج الحجز تلقائياً': 'Fills the booking form automatically',
  'يمنع من يفتح جوالك أن يرى حجوزاتك ومحادثاتك. وليس حمايةً من سرقة الحساب — تلك كلمةُ مرورك.': 'Stops whoever opens your phone from seeing your bookings and chats. It is not protection against account theft — that is your password.',
  'يُرتَّب بحث العميل بالأقرب إليه. ومن لم يضع موقعه يظهر بعد من وضعه.': 'Customer search is ordered by who is nearest. Whoever has not set a location appears after those who have.',
  'يُطلب الرمز': 'Ask for the code',
  'يُطلب الرمز فورَ خروجك من التطبيق': 'The code is asked for as soon as you leave the app',
  'يُطلب فورَ خروجك من التطبيق': 'Asked for as soon as you leave the app',
};
