// جدولُ الإنجليزيّة — مفتاحُه النصُّ العربيُّ نفسُه.
//
// **وما لا يُوجد هنا يُعرض بالعربيّة**، لا برمزٍ ولا بفراغ. فالجدولُ ينمو
// دفعةً بعد دفعة والتطبيقُ يعمل في كلّ حال — وهذا ما تقيسه
// `i18n_coverage_test.dart`: تُطبع نسبةُ المترجَم، ويُمنع أن تنقص.
//
// **ولا تُترجم أسماءُ الخدمات والمزوّدين والأقسام:** تلك تأتي من قاعدة
// البيانات كما كتبها أصحابُها، ولا شأنَ للتطبيق بها.
//
// ولا يُكتب هنا نصٌّ فيه `$` — ما يحمل قيمةً تُدرَج يُبنى بـ`trf` بنائبٍ
// مرقَّم، لأنّ ترتيبَ الأجزاء يختلف بين اللغتين.
const Map<String, String> englishStrings = {
  'آراء العملاء': 'Customer reviews',
  'أبحث عن خدمات وأخطّط لحفل زفافي': 'I am looking for services and planning my wedding',
  'أبلغنا بالحوالة': 'Report your transfer',
  'أبين': 'Abyan',
  'أحد': 'Sun',
  'أخرى': 'Other',
  'أدخل رمز القفل': 'Enter your lock code',
  'أربعاء': 'Wed',
  'أربعة أرقام': 'Four digits',
  'أرسل': 'Send',
  'أرسل التسجيل': 'Send recording',
  'أرفق': 'Attach',
  'أرقامك': 'Your numbers',
  'أريد تقديم خدمة': 'I want to offer a service',
  'أزل الموقع': 'Remove location',
  'أزل من المفضّلة': 'Remove from favourites',
  'أسماء الخدمات والمزوّدين تبقى كما كتبها أصحابها.':
      'Service and provider names stay as their owners wrote them.',
  'أضف': 'Add',
  'أضف صورة': 'Add a photo',
  'أضف للمفضّلة': 'Add to favourites',
  'أضف ما تقدّمه بسعره وعربونه، ليظهر للعملاء في الاستكشاف.':
      'Add what you offer with its price and deposit, so customers find it in Explore.',
  'أضف ما يوضّح موقفك…': 'Add anything that supports your case…',
  'أضف مقطع فيديو': 'Add a video',
  'أضف مقطعاً صوتياً': 'Add an audio clip',
  'أضف مهمّة…': 'Add a task…',
  'أضِفه إلى خطة العرس': 'Add it to the wedding plan',
  'أطفئه': 'Turn off',
  'أعرض خدماتي وأستقبل الحجوزات': 'I list my services and take bookings',
  'أعلى السعر لا يكون أقلّ من أدناه.': 'The maximum price cannot be below the minimum.',
  'أعِد الرمز للتأكيد': 'Repeat the code to confirm',
  'أغلق اليوم': 'Close this day',
  'أغلقتَه': 'You closed it',
  'أغلقها': 'Close it',
  'أغلقها إن حُلّت مشكلتك. تبقى المحادثة محفوظة، ويمكنك فتح تذكرة جديدة متى شئت.': 'Close it once your problem is solved. The conversation stays saved, and you can open a new ticket any time.',
  'أكمل ملفك': 'Complete your profile',
  'ألغِ التسجيل': 'Cancel recording',
  'أمانة العاصمة': 'Amanat Al-Asimah',
  'أنا عروس': 'I am the bride',
  'أنا عريس': 'I am the groom',
  'أنت': 'You',
  'أنشئ حسابك لتبدأ تجهيز عرسك': 'Create your account and start planning your wedding',
  'أنشئ خطتك': 'Create your plan',
  'أهلاً بك': 'Welcome',
  'أي تفاصيل يحتاجها مقدّم الخدمة': 'Any details the provider needs',
  'أيام': 'days',
  'أُرسل رمزٌ جديد. تحقّق من «المهملات» إن تأخّر.':
      'A new code was sent. Check your spam folder if it is slow.',
  'أُطفئ قفل التطبيق.': 'App lock turned off.',
  'أُغلقت التذكرة.': 'Ticket closed.',
  'أُلغي الحجز.': 'Booking cancelled.',
  'أُوقفت الخدمة': 'Service suspended',
  'إب': 'Ibb',
  'إجمالي الأرباح': 'Total earnings',
  'إجمالي الحجز': 'Booking total',
  'إجمالي الحجوزات': 'Total bookings',
  'إخفاء المنجَز': 'Hide completed',
  'إرسال': 'Send',
  'إرسال التقييم': 'Submit review',
  'إشعارات الحجوزات والرسائل': 'Booking and message notifications',
  'إضافة': 'Add',
  'إعادة المحاولة': 'Try again',
  'إعلان': 'Advertisement',
  'إغلاق': 'Close',
  'إغلاق التذكرة': 'Close ticket',
  'إكمال المبلغ': 'Pay the balance',
  'إلغاء': 'Cancel',
  'إلغاء الحجز': 'Cancel booking',
  'إلى (اختياري)': 'To (optional)',
  'إن كان لديك كود': 'If you have a code',
  'إنشاء الحساب': 'Create account',
  'إنشاء الخطة': 'Create plan',
  'إيقاف': 'Stop',
  'ابحث': 'Search',
  'ابحث عن خدمة': 'Search for a service',
  'ابحث عن خدمة أو مقدّم خدمة': 'Search for a service or provider',
  'ابحث عن قاعة، مصوّر، طبّاخ…': 'Search for a hall, photographer, caterer…',
  'ابحث عن مكان، أو الصق رابطه': 'Search for a place, or paste its link',
  'ابدأ الحديث': 'Start the conversation',
  'ابدأ خطة عرسك': 'Start your wedding plan',
  'ابدأ رحلتك': 'Start your journey',
  'ابدأ من «استكشف» واحجز خدمتك القادمة': 'Start from Explore and book your next service',
  'ابدأ من «استكشف» واختر أول خدمة لعرسك.':
      'Start from Explore and pick the first service for your wedding.',
  'اثنين': 'Mon',
  'اجعله الافتراضي': 'Make it default',
  'اجعلها الافتراضية': 'Make it default',
  'احجز': 'Book',
  'احذف': 'Delete',
  'احذف المهمّة': 'Delete task',
  'احفظ رقم محفظتك مرّةً واحدة، فيملأ نفسه في كل إبلاغٍ بحوالة.':
      'Save your wallet number once and it fills itself in every transfer report.',
  'احفظ عنوان بيت العرس مرّةً واحدة، فيملأ نفسه في كل حجزٍ بعدها.':
      'Save the wedding venue address once and it fills itself in every booking after.',
  'اختر النغمة والاهتزاز من إعدادات جهازك':
      'Choose the sound and vibration from your device settings',
  'اختر الوسيلة التي حوّلت بها.': 'Choose the method you transferred with.',
  'اختر تاريخ العرس': 'Choose the wedding date',
  'اختر تاريخ العرس.': 'Choose the wedding date.',
  'اختر رمزاً من أربعة أرقام': 'Choose a four-digit code',
  'اختر ما يصفك لنبدأ من مكانك الصحيح': 'Pick what describes you so we start in the right place',
  'اختر مقطعاً صوتياً': 'Choose an audio clip',
  'اختر ملفاً': 'Choose a file',
  'اختر من المعرض': 'Choose from gallery',
  'اختر نوع الحساب': 'Choose your account type',
  'اختيار من المعرض': 'Choose from gallery',
  'اختياري — ويوفّر على مقدّم الخدمة أن يتّصل ليسأل عن الطريق':
      'Optional — it saves the provider a call asking for directions',
  'اخرج وأعد الدخول': 'Sign out and back in',
  'اذكر التواريخ والمبالغ وما اتُّفق عليه — هذا ما تنظر فيه الإدارة.':
      'State the dates, the amounts, and what was agreed — this is what the team reviews.',
  'اسأل عن الموعد والسعر وما تشمله الخدمة قبل أن تحجز.':
      'Ask about the date, the price, and what the service includes before you book.',
  'استعادة كلمة المرور': 'Reset password',
  'استكشف': 'Explore',
  'استمع قبل أن تحجز': 'Listen before you book',
  'اسم الخدمة': 'Service name',
  'اسم الخطة': 'Plan name',
  'اسم المحل أو القاعة': 'Shop or hall name',
  'اسم المنشأة': 'Business name',
  'اسم صاحب المحفظة': 'Wallet holder name',
  'اشتراكك': 'Your subscription',
  'اشترك': 'Subscribe',
  'اشرح ما حدث بالتفصيل…': 'Describe what happened in detail…',
  'اشرح مشكلتك بالتفصيل…': 'Describe your problem in detail…',
  'اضغط أيَّ يومٍ لتغلقه إن كان عندك ارتباط.': 'Tap any day to close it if you are busy.',
  'اضغط القلب على أي خدمة في الاستكشاف لتحفظها هنا وتقارن بينها.':
      'Tap the heart on any service in Explore to save it here and compare.',
  'اضغط لإنشاء الخطة': 'Tap to create the plan',
  'اضغط لعرض حجوزاتك': 'Tap to see your bookings',
  'اعتذار': 'Apology',
  'افتح الموقع في الخرائط': 'Open location in Maps',
  'افتح النزاع': 'Open a dispute',
  'افتح خدمةً واضغط «راسل مقدّم الخدمة» لتسأل قبل أن تحجز.':
      'Open a service and tap “Message the provider” to ask before you book.',
  'افتح في الخرائط': 'Open in Maps',
  'افتحه': 'Open',
  'اقتراح': 'Suggestion',
  'اقصصه ثم أعد الرفع.': 'Trim it and upload again.',
  'اكتب اسم الخدمة وسعرها، واختر قسمها.':
      'Enter the service name and price, and choose its category.',
  'اكتب اسم الخطة، واختر تاريخ العرس ومحافظته.':
      'Enter the plan name, and choose the wedding date and governorate.',
  'اكتب اسم المنشأة ورقمك، واختر محافظتك وقسماً واحداً على الأقل.':
      'Enter your business name and phone, and choose your governorate and at least one category.',
  'اكتب اسم محلّك أو قاعتك.': 'Enter your shop or hall name.',
  'اكتب اسمك كاملاً.': 'Enter your full name.',
  'اكتب اسمك ورقمك واختر محافظتك.': 'Enter your name and phone, and choose your governorate.',
  'اكتب البريد وكلمة المرور.': 'Enter your email and password.',
  'اكتب الرمز الواصل إلى بريدك.': 'Enter the code sent to your email.',
  'الإشعارات': 'Notifications',
  'الإصدار 1.0.0': 'Version 1.0.0',
  'الإعدادات': 'Settings',
  'الاسم الكامل': 'Full name',
  'الافتراضي': 'Default',
  'البريد الإلكتروني': 'Email',
  'البيضاء': 'Al-Bayda',
  'التقاط صورة': 'Take a photo',
  'التقييم': 'Rating',
  'الجوف': 'Al-Jawf',
  'الحديدة': 'Al-Hudaydah',
  'الحساب واحد — تستطيع أن تعرض خدماتك لاحقاً أو أن تحجز، أيّاً كان اختيارك':
      'One account either way — you can list services later, or book, whatever you choose',
  'الدعم': 'Support',
  'الرئيسية': 'Home',
  'الرمز أربعة أرقام.': 'The code is four digits.',
  'الرمزان غير متطابقين — لم يُفعَّل القفل.':
      'The codes do not match — the lock was not turned on.',
  'السبب': 'Reason',
  'السبب (اختياري)': 'Reason (optional)',
  'السعر': 'Price',
  'الصور': 'Photos',
  'الضالع': 'Ad-Dali',
  'الطلبات': 'Requests',
  'العروض والإعلانات': 'Offers and promotions',
  'العناوين': 'Addresses',
  'العنوان': 'Address',
  'العودة إلى وضع العميل': 'Back to customer mode',
  'القفل مطفأ': 'Lock is off',
  'القفل مفعّل': 'Lock is on',
  'الكريمي': 'Al-Kuraimi',
  'الكل': 'All',
  'اللغة': 'Language',
  'المحادثات': 'Chats',
  'المحافظة': 'Governorate',
  'المحويت': 'Al-Mahwit',
  'المدفوع': 'Paid',
  'المفضّلة': 'Favourites',
  'المكلا': 'Mukalla',
  'المهرة': 'Al-Mahrah',
  'الميزانية': 'Budget',
  'النزاعات': 'Disputes',
  'الوحدة': 'Unit',
  'بعد خمس دقائق': 'After five minutes',
  'بعد دقيقة': 'After a minute',
  'بعد ربع ساعة': 'After fifteen minutes',
  'بعد ساعة': 'After an hour',
  'تراجع': 'Undo',
  'تسجيل الخروج': 'Sign out',
  'تسجيل الخروج؟': 'Sign out?',
  'تعديل': 'Edit',
  'تعديل الخطة': 'Edit plan',
  'تعذّر تشغيل المقطع': 'Could not play the clip',
  'تعذّر فتح الرابط — افتح {0} في متصفّحك.': 'Could not open the link — open {0} in your browser.',
  'تعز': 'Taiz',
  'تقويمي': 'My calendar',
  'ثانية': 'second',
  'ثلاثاء': 'Tue',
  'ثمانية أحرف فأكثر.': 'Eight characters or more.',
  'جديد': 'New',
  'جرّب قسماً آخر أو امسح البحث.': 'Try another category or clear the search.',
  'جمعة': 'Fri',
  'جوالي': 'Jawali',
  'حجة': 'Hajjah',
  'حجوزاتي': 'My bookings',
  'حذف': 'Delete',
  'حسابي': 'My account',
  'حضرموت': 'Hadhramaut',
  'حفظ': 'Save',
  'حوالة بنكية': 'Bank transfer',
  'حوّل إلى': 'Transfer to',
  'حوّلتُ المبلغ — أبلغ الإدارة': 'I sent the money — notify the team',
  'خدماتي': 'My services',
  'خدمة جديدة': 'New service',
  'خروج': 'Sign out',
  'خطة العرس': 'Wedding plan',
  'خميس': 'Thu',
  'دقيقة': 'minute',
  'ذمار': 'Dhamar',
  'رابط التنزيل غير صالح — راجع الإدارة.': 'The download link is not valid — contact support.',
  'رقم الجوال': 'Phone number',
  'رمزٌ خاطئ — بقيت {0} محاولات.': 'Wrong code — {0} attempts left.',
  'ريمة': 'Raymah',
  'ساعة': 'hour',
  'سبت': 'Sat',
  'ستحتاج إلى بريدك وكلمة مرورك للدخول مرّةً أخرى.':
      'You will need your email and password to sign in again.',
  'سقطرى': 'Socotra',
  'سياسة الخصوصية': 'Privacy policy',
  'سيُغلق حسابُك على هذا الجهاز ويُزال القفل. وتدخل من جديد ببريدك وكلمة مرورك. ولا يضيع شيءٌ من حجوزاتك ولا محادثاتك — كلُّها في حسابك لا في الجهاز.': 'You will be signed out on this device and the lock removed. Sign back in with your email and password. Nothing is lost — your bookings and chats live in your account, not on the device.',
  'شبوة': 'Shabwah',
  'شروط الاستخدام': 'Terms of use',
  'صدرت نسخة {0}': 'Version {0} is out',
  'صعدة': 'Saada',
  'صنعاء': 'Sana’a',
  'صورة': 'Photo',
  'طرق الدفع': 'Payment methods',
  'طلب حذف الحساب': 'Request account deletion',
  'عدد الضيوف': 'Guests',
  'عدن': 'Aden',
  'عمران': 'Amran',
  'عميل': 'Customer',
  'عن التطبيق': 'About',
  'عنوان جديد': 'New address',
  'فعّله': 'Turn on',
  'فواتيري': 'My invoices',
  'فوراً': 'Immediately',
  'فُعّل قفل التطبيق.': 'App lock turned on.',
  'قفل التطبيق': 'App lock',
  'قيد التأكيد': 'Awaiting confirmation',
  'قيد المراجعة': 'Under review',
  'كلمة المرور قصيرة جداً (8 أحرف على الأقل).': 'Password is too short (8 characters minimum).',
  'لا بدّ من التحديث': 'Update required',
  'لا حجوزات قادمة': 'No upcoming bookings',
  'لاحقاً': 'Later',
  'لحج': 'Lahij',
  'للحجز': 'per booking',
  'لم تُضبط وسائل التحويل بعد': 'No transfer methods set up yet',
  'لم يصلني — أعد الإرسال': 'I did not get it — resend',
  'مأرب': 'Marib',
  'محجوز': 'Booked',
  'مرحباً بك في فرحتي': 'Welcome to Farhati',
  'مرفوض': 'Rejected',
  'مستحقّاتي': 'My earnings',
  'مستندات التوثيق': 'Verification documents',
  'مقدّم الخدمة': 'Service provider',
  'مقدّم خدمة': 'Service provider',
  'مقطع صوتي': 'Voice note',
  'ملف': 'File',
  'ملفي': 'My profile',
  'مميّز': 'Featured',
  'موقع المحلّ': 'Shop location',
  'موقوفة': 'Suspended',
  'نزّل التحديث': 'Download the update',
  'نزّلها': 'Download',
  'نسختُك لم تعد تعمل مع الخدمة. نزّل نسخة {0} لتُكمل.': 'Your version no longer works with the service. Download version {0} to continue.',
  'نسيتَ الرمز؟': 'Forgot your code?',
  'نسيتُ الرمز': 'I forgot the code',
  'نغمة الإشعار': 'Notification sound',
  'وسيلة جديدة': 'New method',
  'يمنع من يفتح جوالك أن يرى حجوزاتك ومحادثاتك. وليس حمايةً من سرقة الحساب — تلك كلمةُ مرورك.': 'Stops whoever opens your phone from seeing your bookings and chats. It is not protection against account theft — that is your password.',
  'يُطلب الرمز': 'Ask for the code',
};
